### ISSUE TITLE
Support system without sudo

### ISSUE THREAD

**Issue by hroncok** [leamas/lpf#19]
Hi,
I'm nut using sudo and currenty I can either run lpf as user. Then I'm prompted for my password and then sudo fails.

I can run lpf as root, but then I'm prompted for my password (root) witch is pointless.

Please support PolicyKit instead of sudo, as PolicyKit supports both sudo and root password.

If you have no clue, how to do it, just run pkexec instead of sudo. It will prompt for password either in terminal or using graphical user interface dialog when DISPALY is available.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/leamas/lpf/issues/19#issuecomment-32644081

Is this issue the source of needing to log out and then back in to use `lpf` upon first installation? All modern software I've used delegates this task to PolicyKit, which merely invokes a graphical window requesting the password, so that there isn't a group for every application that requires elevation.
